server:
  port: 8080

my:
  name: victor
  age: 20
  number: ${random.int}
  uuid: ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  greeting: hi,i'm ${my.name}

spring:
  profiles:
    active: dev