server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update  #第一次建表用create ,后面用update
    show-sql: true
  redis:
    host: localhost
    port: 6379
    password: longshine
    database: 1   #选择了序号为1的库



